### ISSUE TITLE
Add Deezy Class using API

### ISSUE THREAD

**Issue by nullcount** [nullcount/rain#25]
All endpoints are appreciated, but start with the EARN endpoints
https://docs.deezy.io/#tag/Earn

create a class Deezy in  deezy.py
Create methods for each endpoint
Deezy API follows the OpenAPI standard, not sure if there's any tooling to generate the methods for you or if it's more of a Documentation thing. 

This is the first step towards implementing a Deezy Auto Earn strategy see #7

**Comment by count-null** [comment]
there's already this you can steal from: https://github.com/dannydeezy/deezy-py
