### ISSUE TITLE
Cost aware rebalancing - prerequisites 

### ISSUE THREAD

**Issue by nullcount** [nullcount/rain#62]
Currently, each node to open channels with has a dedicated loop-out operator assigned to it. This makes sense when the loop-out operator is also the node you're sharing channels with. However, if connected to a non-loop-out node, different loop-out operators may be cheaper at different times (depending on liquidity in farther hops). 

It would be great if every channel could calculate the costs of looping out via every possible loop-out method.

- each loop out operator needs a method to calculate the fees associated with a loop out of X satoshis. It should return the fees associated with the operator itself that cannot be gleaned from the P2P network graph, or miner fees alone. (e.x. kraken charges 1000sat flat fee for onchain widthdawls and deezy charges a ppm rate plus whatever onchain fee is chosen)

- LND needs a new method for probing invoices to calculate the network fee before sending payment

These can be combined in the channel manager to calculate the fee of a loop-out before engaging. Another issue will track the actual implementation in the strategy.

**Comment by count-null** [comment]
To calculate the fee before paying a Lightning invoice, you can use the ProbeByPaymentHash method in the LND gRPC API. This method returns a ProbePaymentResponse object, which includes a route field that contains information about the route that the payment would take through the network. The route field is a list of RouteHop objects, each of which represents a hop in the payment's path through the network.

To calculate the fee for the payment, you can sum the fee field of each RouteHop object in the route list. This will give you the total fee that would be charged for the payment.

Here is an example of how you could use the ProbeByPaymentHash method in Python to calculate the fee for a Lightning invoice:

```
import grpc
from lnd_grpc import lightning_pb2_grpc, lightning_pb2

# Connect to the LND gRPC server
channel = grpc.insecure_channel('localhost:10009')
stub = lightning_pb2_grpc.LightningStub(channel)

# Take a lightning invoice string and convert it to a payment hash
invoice = 'your_invoice_string_here'
payment_hash = invoice_string_to_payment_hash(invoice)

# Call the ProbeByPaymentHash method to get a ProbePaymentResponse object
response = stub.ProbeByPaymentHash(lightning_pb2.ProbePaymentHashRequest(
    payment_hash=payment_hash
))

# Sum the fee of each hop in the route to get the total fee
total_fee = sum([hop.fee for hop in response.route.hops])

print(f'Total fee for payment: {total_fee} satoshis')
```

**Comment by count-null** [comment]
```
import grpc
from lnd import lnrpc_pb2, lnrpc_pb2_grpc

def pay_invoice_with_invalid_hash(invoice: str, lnd_grpc_address: str, macaroon_path: str):
    # Create a gRPC channel to the LND node
    with open(macaroon_path, 'rb') as f:
        macaroon_bytes = f.read()
    macaroon = macaroon_bytes.hex()
    creds = grpc.ssl_channel_credentials()
    channel = grpc.secure_channel(lnd_grpc_address, creds)
    stub = lnrpc_pb2_grpc.LightningStub(channel)

    # Create a request to pay the invoice
    request = lnrpc_pb2.SendRequest(payment_request=invoice)

    # Add an invalid payment hash to the request
    request.payment_hash = b'\x01' * 32

    # Send the request to pay the invoice
    try:
        response = stub.SendPaymentSync(request)
    except grpc.RpcError as e:
        if e.code() == grpc.StatusCode.INVALID_ARGUMENT:
            print('Payment failed: Invalid payment hash')
            return None
        else:
            raise e

    # Return the path of hops used if the payment succeeded
    return response.route.hops
```
